### ISSUE TITLE
Why hardcoded minimum amount of satoshi?

### ISSUE THREAD

**Issue by lordscales91** [maraoz/proofofexistence#25]
I've been looking at the code but didn't understand why you need to stablish a minimum amount of satoshis, or why that minimum is so high. It's 5mBTC instead of the 0.1mBTC that are really needed for paying the transaction fees. I could understand it if you say that you are charging a fee for the service, but on the payment page you say "You'll need to pay 5 mBTC to do so, required by our embedding algorithm, and you are also invited to tip us with whatever value you find appropiate."

It feels like a scam to me, I don't see a REAL requirement for that amount, instead I see a hardcoded value. Could you please explain this?

**Comment by qm3ster** [comment]
It's currently  5 mBTC to embed (over a year later)
Is this intentional?

**Comment by maraoz** [comment]
The cost of the service is and always was 5 mBTC. I changed the wording to better explain the costs back then, but I didn't mean to update the price.

**Comment by qm3ster** [comment]
Oh. I don't have any beef with that pricetag per se, but the message is exactly as quoted by @lordscales91, `You'll need to pay 5 mBTC to do so, required by our embedding algorithm, and you are also invited to tip us with whatever value you find appropiate.`
Down to the typo in the word approp**r**iate.
To me that reads like the algorithm spends 5mBTC on recording the transaction, such as by sending multiple minimum transfers to record more data into the blockchain. Says nothing about the existing pre-tip compensation to the owner (which I agree should exist to reward them for providing the service and banaly pay for hosting).

**Comment by maraoz** [comment]
Oops, my bad! I thought I had changed that, but it looks like I only changed the wording in the home page. I'll look into that, thanks!

**Comment by maraoz** [comment]
Done!
